### PR TITLE
feat(gsoc'24): report as spam and moderation review page

### LINKED ISSUE #17: Moderation Tools and Spam detection and Language Filters
Task
- [x] Report as Spam feature with moderator only route to view all reported forum posts
- [x] Adding Language filter to avoid  profanity, sex, violence, hate speech etc

### PR DESCRIPTION
**Pull request by Waishnav**
Fixes #17 

This PR's covers following functionality
- improvised UI for actions like delete, edit, report spam, mark as solution using dropdown.
- authenticated user can report any forum post as spam for review
- moderators can delete reported spam post from moderators only route. `threads/spam_reports`

**Note**: For client side interaction like **dropdown toggle**, **report spam modal form**, javascript was needed so I've used hotwire stimulus controllers for this. and currently build files of these javascript assets are not pushed but to use this rails engine in production, we have to push these javascripts assets with the rails engine.   

Screenshots:

image
image
image
image

### CODE REVIEW

**Comment by tachyons** [comment]
Could you resolve the conflicts ?  Also not all of these messages are [spam](https://en.wikipedia.org/wiki/Spamming). Make spam as a category and rename the text as "Report post". 

Also don't push mark as solution to the dropdown, it's visibility will decrease.

**Comment by Waishnav** [comment]
> Also don't push mark as solution to the dropdown, it's visibility will decrease.

Yeah agreed with your point, but if we add this button in the forum post's footer, it will make post more crowdy with this action button.

Since all action regarding the forum post is now grouped using this dropdown, it just matter of time user will adopt to this feature as they gets used to this forum card layout. wdyt?

**Comment by Waishnav** [comment]
image

@tachyons made that `mark as solution` and `unmark as solution` button visible outside of dropdown. Now it will be shown in the forum post's header like this.

**Comment by Waishnav** [comment]
@tachyons I've added new tests for new functionality which I added. can you please re-review this PR

**Pull request merged**
